      SUBROUTINE KEPLER(XM,EC,ECAN,TR)
c  Version of October 6, 1995
      IMPLICIT REAL*8(A-H,O-Z)
      TOL=1.d-8
      DLECAN=0.D0
      ECAN=XM
   18 ECAN=ECAN+DLECAN
      XMC=ECAN-EC*DSIN(ECAN)
      DEDM=1.D0/(1.D0-EC*DCOS(ECAN))
      DLECAN=(XM-XMC)*DEDM
      ABDLEC=DABS(DLECAN)
      IF(ABDLEC.GT.TOL) GOTO 18
      TR=2.D0*DATAN(DSQRT((1.D0+EC)/(1.D0-EC))*DTAN(.5D0*ECAN))
      IF(TR.LT.0.) TR=TR+6.2831853071795865d0
      RETURN
      END
