language: python

os:
    - linux

sudo: false

env:
    global:
        # Set defaults to avoid repeating in most cases
        - PYTHON_VERSION=2.7
        - NUMPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - CONDA_DEPENDENCIES='scipy matplotlib'
        - PIP_DEPENDENCIES=''

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        # - PYTHON_VERSION=3.3 SETUP_CMD='egg_info'
        # - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        # - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try MacOS X
        - os: osx
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES=$CONDA_ALL_DEPENDENCIES


        # Try with various versions of numpy/astropy
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10 ASTROPY_VERSION=1.0 SETUP_CMD='test --open-files'
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=stable ASTROPY_VERSION=stable SETUP_CMD='test --open-files'


    allow_failures:
      - env: NUMPY_VERSION=dev SETUP_CMD='test'



install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh


script:
    - $MAIN_CMD $SETUP_CMD
