#ifndef PHOEBE_GUI_GLOBAL_H
	#define PHOEBE_GUI_GLOBAL_H 1

/* Detached windows flags */

gboolean PHOEBE_WINDOW_SIDESHEET_IS_DETACHED = FALSE;
gboolean PHOEBE_WINDOW_LC_PLOT_IS_DETACHED = FALSE;
gboolean PHOEBE_WINDOW_RV_PLOT_IS_DETACHED = FALSE;
gboolean PHOEBE_WINDOW_FITTING_IS_DETACHED = FALSE;

#endif
