#include <gtk/gtk.h>
#include <glade/glade.h>

void on_phoebe_test_toolbutton_0_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_test_toolbutton_1_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_open_toolbutton_clicked 						(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_save_toolbutton_clicked 						(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_fitting_toolbutton_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_scripter_toolbutton_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_settings_toolbutton_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_quit_toolbutton_clicked 						(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_file_new_menuitem_activate 					(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_file_open_menuitem_activate 					(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_file_save_menuitem_activate 					(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_file_saveas_menuitem_activate 				(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_file_quit_menuitem_activate 					(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_settings_configuration_menuitem_activate 	(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_help_about_menuitem_activate 				(GtkMenuItem *menuitem, gpointer user_data);
void on_phoebe_data_lc_treeview_row_activated 				(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_data_lc_active_checkbutton_toggled 			(GtkCellRendererToggle *renderer, gchar *path, gpointer user_data);
void on_phoebe_data_lc_add_button_clicked 					(GtkButton *button, gpointer user_data);
void on_phoebe_data_lc_edit_button_clicked 					(GtkButton *button, gpointer user_data);
void on_phoebe_data_lc_remove_button_clicked 				(GtkButton *button, gpointer user_data);
void on_phoebe_data_lc_model_row_changed 					(GtkTreeModel *tree_model, GtkTreePath  *path, GtkTreeIter *iter, gpointer user_data);
void on_phoebe_data_rv_treeview_row_activated 				(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_data_rv_add_button_clicked 					(GtkButton *button, gpointer user_data);
void on_phoebe_data_rv_edit_button_clicked 					(GtkButton *button, gpointer user_data);
void on_phoebe_data_rv_remove_button_clicked 				(GtkButton *button, gpointer user_data);
void on_phoebe_data_rv_active_checkbutton_toggled 			(GtkCellRendererToggle *renderer, gchar *path, gpointer user_data);
void on_phoebe_data_rv_model_row_changed 					(GtkTreeModel *tree_model, GtkTreePath  *path, GtkTreeIter *iter, gpointer user_data);
void on_phoebe_para_spots_adjust_checkbutton_toggled 		(GtkCellRendererToggle *renderer, gchar *path, gpointer user_data);
void on_phoebe_para_spots_active_checkbutton_toggled 		(GtkCellRendererToggle *renderer, gchar *path, gpointer user_data);
void on_phoebe_para_spots_addprim_button_clicked 			(GtkButton *button, gpointer user_data);
void on_phoebe_para_spots_addsec_button_clicked 			(GtkButton *button, gpointer user_data);
void on_phoebe_para_spots_remove_button_clicked 			(GtkButton *button, gpointer user_data);
void on_phoebe_para_lum_levels_treeview_row_activated 		(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_para_lum_levels_edit_button_clicked 			(GtkButton *button, gpointer user_data);
void on_phoebe_para_lum_el3_treeview_row_activated 			(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_para_lum_weighting_treeview_row_activated 	(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_para_lum_weighting_edit_button_clicked 		(GtkButton *button, gpointer user_data);
void on_phoebe_para_ld_lccoefs_edit_button_clicked 			(GtkButton *button, gpointer user_data);
void on_phoebe_para_ld_lccoefs_treeview_row_activated 		(GtkTreeView *treeview, GtkTreePath *path, GtkTreeViewColumn *column, gpointer user_data);
void on_phoebe_load_lc_filechooserbutton_selection_changed 	(GtkFileChooserButton *filechooserbutton, gpointer user_data);
void on_phoebe_load_rv_filechooserbutton_selection_changed 	(GtkFileChooserButton *filechooserbutton, gpointer user_data);
void on_phoebe_lc_plot_detach_button_clicked 				(GtkButton *button, gpointer user_data);
void on_phoebe_settings_toolbutton_clicked 					(GtkToolButton *toolbutton, gpointer user_data);
void on_phoebe_settings_checkbutton_toggled 				(GtkToggleButton *togglebutton, gpointer user_data);
void on_phoebe_fitt_updateall_button_clicked 				(GtkToolButton   *toolbutton, gpointer user_data);
