CC=g++
CXXFLAGS=-O3 -Wall -std=c++11

all:triang_marching sphere_area_volume

%:%.cpp *.h
	$(CC) $(CXXFLAGS) $*.cpp -o $*

#triang_marching:triang_marching.cpp
#	$(CC) triang_marching.cpp -o triang_marching $(CXXFLAGS)
