name: Release

on:
    workflow_dispatch:
    pull_request:
    release:
        types: [created]

jobs:
    build-sdist:
        name: Package source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build sdist tarball
              run: |
                pipx run build --sdist
            - uses: actions/upload-artifact@v4
              with:
                name: cibw-sdist
                path: dist/*.tar.gz

    build-wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, macos-13, macos-14]
        steps:
            - name: Checkout the sources
              uses: actions/checkout@v4
            - name: Build wheels
              uses: pypa/cibuildwheel@v2.21.2
              env:
                CIBW_SKIP: pp37-* pp38-* pp39-* pp31*-macosx*
            - uses: actions/upload-artifact@v4
              with:
                name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl

    publish-to-pypi:
        if: github.event_name != 'pull_request'
        needs: [build-sdist, build-wheels]
        name: Publish release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/phoebe
        permissions:
            id-token: write
        steps:
            - name: Gather sdist tarball and wheels
              uses: actions/download-artifact@v4
              with:
                pattern: cibw-*
                path: dist
                merge-multiple: true
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1